import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from './api-client';
import type { DashboardStats, Paginated, Project, Task } from './types';

export function useDashboardStats() { return useQuery({ queryKey:['dashboard'], queryFn:()=>apiRequest<DashboardStats>('/api/dashboard/stats') }); }
export function useProjects(params: {search?:string;status?:string;page?:number;limit?:number}={}) { return useQuery({queryKey:['projects',params],queryFn:()=>apiRequest<Paginated<Project>>('/api/projects',{query:{...params,status:params.status==='ALL'?undefined:params.status}})}); }
export function useProject(id:string){return useQuery({queryKey:['project',id],queryFn:()=>apiRequest<Project>(`/api/projects/${id}`),enabled:!!id});}
export function useTasks(params:{projectId?:string;search?:string;status?:string;priority?:string;page?:number;limit?:number}={}){return useQuery({queryKey:['tasks',params],queryFn:()=>apiRequest<Paginated<Task>>('/api/tasks',{query:{...params,status:params.status==='ALL'?undefined:params.status,priority:params.priority==='ALL'?undefined:params.priority}}),enabled:!!params.projectId});}
export function useCreateProject(){const q=useQueryClient();return useMutation({mutationFn:(input:any)=>apiRequest<Project>('/api/projects',{method:'POST',body:input}),onSuccess:()=>{q.invalidateQueries({queryKey:['projects']});q.invalidateQueries({queryKey:['dashboard']});}})}
export function useUpdateProject(){const q=useQueryClient();return useMutation({mutationFn:({id,input}:{id:string;input:any})=>apiRequest<Project>(`/api/projects/${id}`,{method:'PUT',body:input}),onSuccess:(_,v)=>{q.invalidateQueries({queryKey:['projects']});q.invalidateQueries({queryKey:['project',v.id]});q.invalidateQueries({queryKey:['dashboard']});}})}
export function useDeleteProject(){const q=useQueryClient();return useMutation({mutationFn:(id:string)=>apiRequest<void>(`/api/projects/${id}`,{method:'DELETE'}),onSuccess:()=>{q.invalidateQueries({queryKey:['projects']});q.invalidateQueries({queryKey:['dashboard']});}})}
export function useCreateTask(){const q=useQueryClient();return useMutation({mutationFn:(input:any)=>apiRequest<Task>('/api/tasks',{method:'POST',body:input}),onSuccess:()=>{q.invalidateQueries({queryKey:['tasks']});q.invalidateQueries({queryKey:['dashboard']});q.invalidateQueries({queryKey:['projects']});}})}
export function useUpdateTask(){const q=useQueryClient();return useMutation({mutationFn:({id,input}:{id:string;input:any})=>apiRequest<Task>(`/api/tasks/${id}`,{method:'PUT',body:input}),onSuccess:()=>{q.invalidateQueries({queryKey:['tasks']});q.invalidateQueries({queryKey:['dashboard']});q.invalidateQueries({queryKey:['projects']});}})}
export function useDeleteTask(){const q=useQueryClient();return useMutation({mutationFn:(id:string)=>apiRequest<void>(`/api/tasks/${id}`,{method:'DELETE'}),onSuccess:()=>{q.invalidateQueries({queryKey:['tasks']});q.invalidateQueries({queryKey:['dashboard']});q.invalidateQueries({queryKey:['projects']});}})}
