import { Link, useLocation, useNavigate } from '@tanstack/react-router';
import { useState } from 'react';
import { useAuth } from '@/lib/auth';
import { LayoutDashboard, FolderKanban, User, BookOpen, LogOut, Menu, X } from 'lucide-react';

export function AppShell({children}:{children:React.ReactNode}){
 const {user,logout}=useAuth(); const nav=useNavigate(); const loc=useLocation(); const [open,setOpen]=useState(false);
 const links=[['Dashboard','/dashboard',LayoutDashboard],['Projects','/projects',FolderKanban],['Profile','/profile',User],['API Docs','/docs',BookOpen]] as const;
 const signOut=async()=>{await logout();nav({to:'/login'});};
 const content=<><div className="flex items-center gap-3 px-2 pb-7"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-900 text-white shadow-sm"><FolderKanban size={20}/></div><div><div className="font-bold tracking-tight">FlowPulse</div><div className="text-xs text-slate-500">Project Management</div></div></div><nav className="space-y-1">{links.map(([name,href,Icon])=><Link key={href} to={href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${loc.pathname.startsWith(href)?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100'}`}><Icon size={18}/>{name}</Link>)}</nav></>;
 return <div className="min-h-screen bg-slate-50 text-slate-900 md:flex"><aside className="hidden w-64 shrink-0 border-r bg-white p-5 md:block"><div className="sticky top-5 flex h-[calc(100vh-40px)] flex-col"><div>{content}</div><div className="mt-auto border-t pt-4"><div className="mb-3 truncate px-2 text-sm font-medium">{user?.fullName}</div><button onClick={signOut} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-red-600 hover:bg-red-50"><LogOut size={18}/>Sign out</button></div></div></aside><div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur md:hidden"><button onClick={()=>setOpen(true)} className="rounded-lg p-2 hover:bg-slate-100"><Menu/></button><span className="font-bold">FlowPulse</span><button onClick={signOut} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><LogOut size={18}/></button></header>{open&&<div className="fixed inset-0 z-50 md:hidden"><div className="absolute inset-0 bg-black/30" onClick={()=>setOpen(false)}/><aside className="relative h-full w-72 bg-white p-5 shadow-xl"><button className="absolute right-4 top-4" onClick={()=>setOpen(false)}><X/></button>{content}<button onClick={signOut} className="mt-8 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-red-600 hover:bg-red-50"><LogOut size={18}/>Sign out</button></aside></div>}<main className="mx-auto w-full max-w-7xl p-4 md:p-8">{children}</main></div></div>;
}
